//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingClub.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        public int OrderServiceID { get; set; }
        public int OrderID { get; set; }
        public int PricelistID { get; set; }
        public byte Count { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Pricelist Pricelist { get; set; }
    }
}
